import Alpine from 'alpinejs'
import './style.css'

window.Alpine = Alpine

const menu = [
  { id: 1, name: 'Paket Paha Juara', price: 32000, category: 'rekomendasi', emoji: '🍗', tag: 'BEST SELLER', desc: 'Ayam krispi, nasi, minum' },
  { id: 2, name: 'Paket Dada Mantap', price: 36000, category: 'rekomendasi', emoji: '🍗', tag: 'FAVORIT', desc: 'Ayam besar, nasi, minum' },
  { id: 3, name: 'Krispi Berdua', price: 58000, category: 'paket', emoji: '🍗', tag: 'HEMAT', desc: '2 ayam, 2 nasi, 2 minum' },
  { id: 4, name: 'Paket Sultan', price: 72000, category: 'paket', emoji: '🍗', tag: 'RAMAI-RAMAI', desc: '4 ayam, nasi, 2 minum' },
  { id: 5, name: 'Ayam Krispi', price: 17000, category: 'alacarte', emoji: '🍗', tag: '', desc: 'Renyah sampai tulang' },
  { id: 6, name: 'Nasi Hangat', price: 8000, category: 'alacarte', emoji: '🍚', tag: '', desc: 'Porsi pas, pulen' },
  { id: 7, name: 'Pepsi Dingin', price: 9000, category: 'minuman', emoji: '🥤', tag: '', desc: 'Segarnya nggak kaleng-kaleng' },
  { id: 8, name: 'Es Teh Bahagia', price: 7000, category: 'minuman', emoji: '🧋', tag: '', desc: 'Manisnya pas' },
  { id: 9, name: 'Kentang Nyemil', price: 12000, category: 'cemilan', emoji: '🍟', tag: '', desc: 'Kentang gurih bergelombang' },
  { id: 10, name: 'Kulit Krispi', price: 14000, category: 'cemilan', emoji: '✨', tag: 'BARU', desc: 'Tipis, kriuk, nagih' },
]

const dict = {
  id: { order: 'MULAI PESANAN', subtitle: 'Tap layar, pesananmu nggak pakai antre.', choose: 'Pilih pengalamanmu', language: 'Pilih bahasa', eat: 'Makan di mana?', dine: 'Makan di sini', take: 'Bawa pulang', continue: 'Lanjut', menu: 'Menu pilihanmu', reset: 'Reset pesanan', viewCart: 'Lihat pesanan saya', add: 'Tambah', cancel: 'Batalkan', cart: 'Pesanan saya', finish: 'Selesaikan pesanan', more: 'Tambah pesanan', delivery: 'Mau pesanannya ke mana?', table: 'Antar ke meja', counter: 'Ambil di kasir', pay: 'Lanjut ke pembayaran', payment: 'Pilih cara bayarmu', simulate: 'Simulasi sukses', thank: 'Terima kasih!', processing: 'Pesananmu sedang diproses', receipt: 'Struk digital', queue: 'Nomor antrean', back: 'Kembali', items: 'item', tableNo: 'Nomor meja', chooseCut: 'Pilih potongan ayam', chooseDrink: 'Pilih minuman', chooseSauce: 'Pilih saus', addCart: 'Tambah ke keranjang', added: 'Menu ditambahkan!', ready: 'Sudah siap?', scan: 'Scan QR untuk bayar', cash: 'Bayar di kasir', served: 'Akan diantar ke meja' },
  en: { order: 'START ORDER', subtitle: 'Tap the screen, no queue needed.', choose: 'Choose your experience', language: 'Choose language', eat: 'Where are you eating?', dine: 'Dine in', take: 'Take away', continue: 'Continue', menu: 'Your menu picks', reset: 'Reset order', viewCart: 'View my order', add: 'Add', cancel: 'Cancel', cart: 'My order', finish: 'Finish order', more: 'Add more items', delivery: 'Where should we send it?', table: 'Deliver to table', counter: 'Pick up at counter', pay: 'Continue to payment', payment: 'Choose payment method', simulate: 'Simulate success', thank: 'Thank you!', processing: 'Your order is being prepared', receipt: 'Digital receipt', queue: 'Queue number', back: 'Back', items: 'items', tableNo: 'Table number', chooseCut: 'Choose chicken cut', chooseDrink: 'Choose a drink', chooseSauce: 'Choose a sauce', addCart: 'Add to order', added: 'Menu added!', ready: 'Ready?', scan: 'Scan QR to pay', cash: 'Pay at counter', served: 'Will be delivered to your table' }
}

document.querySelector('#app').innerHTML = `
<div x-data="kiosk()" @click.window="touch()" @keydown.window="touch()" class="min-h-screen bg-[#f6f1e8] p-3 sm:p-5 flex items-center justify-center">
  <section class="screen-shell relative overflow-hidden rounded-[2.1rem] bg-[#f7f1e8] border-[8px] border-[#231f20]" aria-label="PahaDada self-ordering kiosk">
    <div class="absolute top-2 left-1/2 -translate-x-1/2 z-50 h-1.5 w-16 rounded-full bg-[#3b3434]"></div>

    <template x-if="step === 'lock'">
      <div class="h-full bg-[#db1f32] text-white grid-noise relative flex flex-col overflow-hidden">
        <div class="absolute -right-24 top-20 h-64 w-64 rounded-full border-[38px] border-[#f5bd27] opacity-95 animate-[spin_18s_linear_infinite]"></div>
        <div class="absolute -left-24 bottom-20 h-44 w-44 rounded-full border-[28px] border-[#ff7e43] opacity-80"></div>
        <header class="relative px-7 pt-10 flex items-center justify-between"><div class="font-black text-2xl tracking-tight">Paha<span class="text-[#f5bd27]">Dada</span><span class="text-sm">.id</span></div><span class="text-[10px] font-bold tracking-[.2em] border border-white/40 rounded-full px-3 py-1">SELF ORDER</span></header>
        <div class="relative flex-1 flex flex-col justify-center px-7 pb-5">
          <div class="mb-5 flex items-center gap-3 text-xs uppercase tracking-[.18em] font-bold"><span class="h-px w-10 bg-[#f5bd27]"></span> Kriuk tanpa ribet</div>
          <h1 class="display text-[4.1rem] leading-[.83] max-w-xs">LAPAR?<br><span class="text-[#f5bd27]">GAS.</span></h1>
          <p class="mt-5 max-w-[15rem] text-sm leading-6 text-white/80" x-text="t('subtitle')"></p>
          <div class="relative mt-6 ml-auto mr-1 food-orb w-44 h-44 rounded-full shadow-2xl flex items-center justify-center text-8xl rotate-[-10deg]">🍗</div>
        </div>
        <div class="relative p-7 pt-2"><button @click="go('preference')" class="w-full rounded-2xl bg-[#f7f1e8] py-5 text-[#d51f32] font-black tracking-wide shadow-xl active:scale-[.98] transition"><i class="fa-solid fa-hand-pointer mr-2"></i><span x-text="t('order')"></span></button><p class="mt-3 text-center text-[10px] tracking-[.12em] text-white/65">TAP TO SKIP THE QUEUE</p></div>
      </div>
    </template>

    <template x-if="step === 'preference'">
      <div class="h-full flex flex-col p-7 bg-[#f7f1e8]">
        <div class="flex justify-between items-center"><button @click="go('lock')" class="text-sm font-bold text-stone-500"><i class="fa-solid fa-arrow-left mr-2"></i><span x-text="t('back')"></span></button><div class="font-black text-xl text-[#d51f32]">PahaDada<span class="text-[#f5bd27]">.id</span></div></div>
        <div class="mt-11"><p class="text-xs font-bold tracking-[.2em] text-[#d51f32]">01 — LET'S START</p><h2 class="display text-4xl mt-2" x-text="t('choose')"></h2></div>
        <div class="mt-7"><p class="font-bold" x-text="t('language')"></p><div class="grid grid-cols-2 gap-3 mt-3"><button @click="language='id'; tap()" :class="language==='id' ? 'border-[#d51f32] bg-red-50' : 'border-stone-200'" class="rounded-2xl border-2 p-4 text-left transition"><span class="text-2xl">🇮🇩</span><span class="block font-bold mt-2">Indonesia</span></button><button @click="language='en'; tap()" :class="language==='en' ? 'border-[#d51f32] bg-red-50' : 'border-stone-200'" class="rounded-2xl border-2 p-4 text-left transition"><span class="text-2xl">🇺🇸</span><span class="block font-bold mt-2">English</span></button></div></div>
        <div class="mt-7"><p class="font-bold" x-text="t('eat')"></p><div class="grid grid-cols-2 gap-3 mt-3"><button @click="orderType='dine'; tap()" :class="orderType==='dine' ? 'bg-[#d51f32] text-white' : 'bg-white border border-stone-200'" class="rounded-2xl p-5 text-left transition"><i class="fa-solid fa-utensils text-xl"></i><span class="block font-bold mt-4" x-text="t('dine')"></span></button><button @click="orderType='take'; tap()" :class="orderType==='take' ? 'bg-[#d51f32] text-white' : 'bg-white border border-stone-200'" class="rounded-2xl p-5 text-left transition"><i class="fa-solid fa-bag-shopping text-xl"></i><span class="block font-bold mt-4" x-text="t('take')"></span></button></div></div>
        <button @click="go('menu')" class="mt-auto bg-[#d51f32] text-white rounded-2xl py-5 font-black shadow-lg" x-text="t('continue')"></button>
      </div>
    </template>

    <template x-if="step === 'menu'">
      <div class="h-full flex flex-col bg-[#f7f1e8]">
        <header class="h-20 shrink-0 flex items-center justify-between px-5 border-b border-stone-200"><div><div class="font-black text-xl text-[#d51f32]">PahaDada<span class="text-[#f5bd27]">.id</span></div><p class="text-[10px] text-stone-500 uppercase tracking-widest" x-text="orderType==='dine' ? t('dine') : t('take')"></p></div><button @click="reset()" class="text-xs font-bold text-stone-500"><i class="fa-solid fa-rotate-left mr-1"></i><span x-text="t('reset')"></span></button></header>
        <div class="px-5 pt-5"><p class="text-xs font-bold tracking-[.18em] text-[#d51f32]">02 — PICK YOUR FAVE</p><h2 class="display text-3xl mt-1" x-text="t('menu')"></h2></div>
        <div class="flex flex-1 min-h-0 mt-4"><nav class="w-[92px] shrink-0 px-3 space-y-2"><template x-for="cat in categories" :key="cat.id"><button @click="category=cat.id; tap()" :class="category===cat.id ? 'bg-[#d51f32] text-white shadow-md' : 'text-stone-500'" class="w-full rounded-xl px-2 py-3 text-[10px] font-bold leading-3 transition"><i :class="cat.icon" class="block text-base mb-1"></i><span x-text="cat.label[language]"></span></button></template></nav>
          <div class="flex-1 pr-4 pb-24 overflow-y-auto scroll-clean"><div class="grid grid-cols-2 gap-3"><template x-for="item in visibleMenu" :key="item.id"><button @click="openItem(item)" class="text-left rounded-2xl bg-white overflow-hidden border border-stone-100 shadow-sm hover:-translate-y-0.5 transition"><div class="h-28 relative flex items-center justify-center mini-food overflow-hidden"><img src="/assets/menu-placeholder.svg" alt="" class="absolute inset-0 h-full w-full object-cover opacity-80"><span x-show="item.tag" class="absolute top-2 left-2 bg-[#f5bd27] px-2 py-1 rounded-full text-[8px] font-black text-[#4c2a14]" x-text="item.tag"></span><span class="relative text-4xl drop-shadow-lg" x-text="item.emoji"></span></div><div class="p-3"><p class="font-black text-xs leading-4" x-text="item.name"></p><p class="text-[10px] text-stone-500 mt-1 truncate" x-text="item.desc"></p><div class="mt-3 flex justify-between items-center"><span class="text-xs font-black text-[#d51f32]" x-text="rupiah(item.price)"></span><span class="h-6 w-6 bg-[#d51f32] text-white rounded-full inline-flex items-center justify-center"><i class="fa-solid fa-plus text-[10px]"></i></span></div></div></button></template></div></div>
        </div>
        <button @click="cart.length && go('cart')" :class="cart.length ? 'bg-[#231f20] text-white' : 'bg-stone-200 text-stone-400'" class="absolute bottom-4 left-4 right-4 rounded-2xl px-5 py-4 flex items-center justify-between shadow-xl"><div class="text-left"><p class="text-[10px] font-bold uppercase tracking-wider" x-text="itemCount + ' ' + t('items')"></p><p class="font-black" x-text="rupiah(total)"></p></div><span class="font-bold text-sm" x-text="t('viewCart')"></span><i class="fa-solid fa-arrow-right"></i></button>
        <div x-show="toast" x-transition class="absolute z-40 top-24 left-1/2 -translate-x-1/2 rounded-full bg-[#268c57] text-white px-5 py-3 shadow-xl font-bold text-sm"><i class="fa-solid fa-check mr-2"></i><span x-text="t('added')"></span></div>
        <div x-show="modal" x-cloak class="absolute inset-0 z-30 bg-black/45 flex items-end" @click.self="modal=false"><div class="bg-[#f7f1e8] w-full rounded-t-[2rem] p-6 animate__animated animate__slideInUp"><div class="flex justify-between"><div><p class="text-xs text-[#d51f32] font-bold tracking-widest">BUILD YOUR BOX</p><h3 class="display text-3xl" x-text="current?.name"></h3></div><button @click="modal=false" class="h-9 w-9 rounded-full bg-stone-200"><i class="fa-solid fa-xmark"></i></button></div><div class="mt-5 space-y-4"><div><p class="font-bold text-sm" x-text="t('chooseCut')"></p><div class="grid grid-cols-2 gap-2 mt-2"><template x-for="choice in ['Paha','Dada']"><button @click="custom.chicken=choice;tap()" :class="custom.chicken===choice ? 'bg-[#d51f32] text-white' : 'bg-white border border-stone-200'" class="rounded-xl p-3 font-bold text-sm" x-text="choice"></button></template></div></div><div><p class="font-bold text-sm" x-text="t('chooseDrink')"></p><div class="grid grid-cols-2 gap-2 mt-2"><template x-for="choice in ['Pepsi','Es Teh']"><button @click="custom.drink=choice;tap()" :class="custom.drink===choice ? 'bg-[#d51f32] text-white' : 'bg-white border border-stone-200'" class="rounded-xl p-3 font-bold text-sm" x-text="choice"></button></template></div></div><div><p class="font-bold text-sm" x-text="t('chooseSauce')"></p><div class="grid grid-cols-2 gap-2 mt-2"><template x-for="choice in ['BBQ','Sambal']"><button @click="custom.sauce=choice;tap()" :class="custom.sauce===choice ? 'bg-[#d51f32] text-white' : 'bg-white border border-stone-200'" class="rounded-xl p-3 font-bold text-sm" x-text="choice"></button></template></div></div></div><button @click="addCurrent()" :disabled="!custom.chicken || !custom.drink || !custom.sauce" class="w-full mt-6 rounded-2xl py-4 bg-[#231f20] text-white disabled:bg-stone-300 font-black" x-text="t('addCart')"></button></div></div>
      </div>
    </template>

    <template x-if="step === 'cart'">
      <div class="h-full flex flex-col bg-[#f7f1e8]"><header class="p-6 pb-4"><button @click="go('menu')" class="text-sm font-bold text-stone-500"><i class="fa-solid fa-arrow-left mr-2"></i><span x-text="t('back')"></span></button><p class="text-xs font-bold tracking-[.18em] text-[#d51f32] mt-5">03 — REVIEW TICKET</p><h2 class="display text-4xl mt-1" x-text="t('cart')"></h2></header><div class="flex-1 overflow-y-auto px-5"><template x-for="(line,index) in cart" :key="line.key"><article class="bg-white rounded-2xl p-4 mb-3 border border-stone-100"><div class="flex gap-3"><div class="mini-food h-12 w-12 rounded-xl flex items-center justify-center text-2xl">🍗</div><div class="flex-1"><p class="font-black text-sm" x-text="line.name"></p><p class="text-[10px] text-stone-500 mt-1" x-text="line.custom.chicken+' · '+line.custom.drink+' · '+line.custom.sauce"></p><p class="font-black text-[#d51f32] text-sm mt-2" x-text="rupiah(line.price * line.qty)"></p></div><div class="flex items-end gap-2"><button @click="changeQty(index,-1)" class="h-7 w-7 rounded-full bg-stone-100"><i class="fa-solid fa-minus text-[10px]"></i></button><span class="font-black text-sm" x-text="line.qty"></span><button @click="changeQty(index,1)" class="h-7 w-7 rounded-full bg-[#d51f32] text-white"><i class="fa-solid fa-plus text-[10px]"></i></button></div></div></article></template></div><footer class="p-5 bg-white border-t border-stone-200"><div class="flex justify-between mb-4"><span class="font-bold text-stone-500">TOTAL</span><span class="text-xl font-black text-[#d51f32]" x-text="rupiah(total)"></span></div><div class="grid grid-cols-2 gap-3"><button @click="go('menu')" class="rounded-xl py-4 bg-stone-100 font-bold text-sm" x-text="t('more')"></button><button @click="go('delivery')" class="rounded-xl py-4 bg-[#d51f32] text-white font-black text-sm" x-text="t('finish')"></button></div></footer></div>
    </template>

    <template x-if="step === 'delivery'">
      <div class="h-full flex flex-col p-6 bg-[#f7f1e8]"><button @click="go('cart')" class="text-sm font-bold text-stone-500 self-start"><i class="fa-solid fa-arrow-left mr-2"></i><span x-text="t('back')"></span></button><p class="text-xs font-bold tracking-[.18em] text-[#d51f32] mt-8">04 — DELIVERY</p><h2 class="display text-4xl mt-1 max-w-xs" x-text="t('delivery')"></h2><div class="space-y-3 mt-7"><button @click="delivery='table';tap()" :class="delivery==='table' ? 'bg-[#d51f32] text-white' : 'bg-white border border-stone-200'" class="w-full rounded-2xl p-5 flex gap-4 text-left"><i class="fa-solid fa-utensils text-xl"></i><span><b class="block" x-text="t('table')"></b><small class="opacity-70">1—99</small></span></button><button @click="delivery='counter';tableNumber='';tap()" :class="delivery==='counter' ? 'bg-[#d51f32] text-white' : 'bg-white border border-stone-200'" class="w-full rounded-2xl p-5 flex gap-4 text-left"><i class="fa-solid fa-store text-xl"></i><span><b class="block" x-text="t('counter')"></b><small class="opacity-70">Pick-up zone</small></span></button></div><template x-if="delivery==='table'"><div class="mt-5"><p class="font-bold text-sm" x-text="t('tableNo')"></p><div class="mt-2 h-16 rounded-xl bg-white border-2 border-[#d51f32] flex items-center px-5 text-2xl font-black" x-text="tableNumber || '—'"></div><div class="grid grid-cols-3 gap-2 mt-3"><template x-for="n in [1,2,3,4,5,6,7,8,9,'clear',0,'delete']"><button @click="keypad(n)" class="rounded-xl bg-white border border-stone-200 py-3 font-black text-sm" x-text="n==='clear'?'C':n==='delete'?'⌫':n"></button></template></div><p x-show="tableNumber && !validTable" class="text-xs font-bold text-[#d51f32] mt-2">Masukkan nomor meja valid (1-99).</p></div></template><button @click="go('payment')" :disabled="!canPay" class="mt-auto rounded-2xl py-5 font-black text-white disabled:bg-stone-300 bg-[#231f20]" x-text="t('pay')"></button></div>
    </template>

    <template x-if="step === 'payment'">
      <div class="h-full flex flex-col p-6 bg-[#f7f1e8]"><button @click="go('delivery')" class="text-sm font-bold text-stone-500 self-start"><i class="fa-solid fa-arrow-left mr-2"></i><span x-text="t('back')"></span></button><p class="text-xs font-bold tracking-[.18em] text-[#d51f32] mt-8">05 — PAYMENT</p><h2 class="display text-4xl mt-1" x-text="t('payment')"></h2><div class="grid grid-cols-3 gap-2 mt-6"><template x-for="method in payments" :key="method.id"><button @click="payment=method.id;tap()" :class="payment===method.id ? 'bg-[#d51f32] text-white border-[#d51f32]' : 'bg-white border-stone-200'" class="rounded-xl border p-3 text-center"><i :class="method.icon" class="text-lg"></i><span class="block text-[10px] font-bold mt-2" x-text="method.label"></span></button></template></div><div class="mt-5 flex-1 rounded-3xl bg-[#231f20] text-white grid-noise p-6 flex flex-col items-center justify-center text-center"><template x-if="payment==='qris'"><div><div class="w-36 h-36 bg-white rounded-xl p-3 grid grid-cols-7 gap-1 mx-auto"><template x-for="x in 49"><i :class="x%3===0 || x%5===0 ? 'bg-[#231f20]' : 'bg-stone-100'" class="rounded-[1px]"></i></template></div><p class="font-black mt-5" x-text="t('scan')"></p></div></template><template x-if="payment==='cash'"><div><i class="fa-solid fa-money-bill-wave text-6xl text-[#f5bd27]"></i><p class="font-black mt-5" x-text="t('cash')"></p></div></template><template x-if="payment && payment!=='qris' && payment!=='cash'"><div><i class="fa-solid fa-mobile-screen-button text-6xl text-[#f5bd27]"></i><p class="font-black mt-5">Follow the instruction<br>on your phone</p></div></template><template x-if="!payment"><div class="text-white/40"><i class="fa-solid fa-arrow-up text-3xl"></i><p class="font-bold mt-3">Pick a payment method</p></div></template><p class="mt-7 text-2xl font-black text-[#f5bd27]" x-text="rupiah(total)"></p></div><button @click="completeOrder()" :disabled="!payment" class="mt-5 rounded-2xl py-4 font-black text-sm text-white disabled:bg-stone-300 bg-[#268c57]" x-text="t('simulate')"></button></div>
    </template>

    <template x-if="step === 'success'">
      <div class="h-full bg-[#d51f32] grid-noise flex items-center justify-center text-white text-center p-8"><div class="animate__animated animate__zoomIn"><div class="h-20 w-20 mx-auto rounded-full border-4 border-[#f5bd27] flex items-center justify-center text-4xl"><i class="fa-solid fa-check"></i></div><h2 class="display text-5xl mt-7" x-text="t('thank')"></h2><p class="mt-3 font-medium text-white/80" x-text="t('processing')"></p></div></div>
    </template>

    <template x-if="step === 'receipt'">
      <div class="h-full p-5 bg-[#d51f32] grid-noise flex items-center"><div class="ticket-edge bg-[#f7f1e8] w-full rounded-sm p-6 shadow-2xl"><div class="text-center border-b-2 border-dashed border-stone-300 pb-5"><p class="font-black text-2xl text-[#d51f32]">PahaDada<span class="text-[#f5bd27]">.id</span></p><p class="text-[10px] tracking-[.2em] mt-1">DIGITAL RECEIPT</p><p class="text-xs mt-4" x-text="t('queue')"></p><h2 class="display text-6xl text-[#d51f32] mt-1" x-text="queueNumber"></h2></div><div class="py-4 border-b-2 border-dashed border-stone-300 text-sm"><template x-for="line in cart" :key="line.key"><div class="mb-3"><div class="flex justify-between font-bold"><span x-text="line.name+' × '+line.qty"></span><span x-text="rupiah(line.price*line.qty)"></span></div><p class="text-[10px] text-stone-500 mt-1" x-text="line.custom.chicken+' · '+line.custom.drink+' · '+line.custom.sauce"></p></div></template></div><div class="py-4 space-y-2 text-sm"><div class="flex justify-between"><span class="text-stone-500">Delivery</span><b x-text="delivery==='table' ? t('served')+' '+tableNumber : t('counter')"></b></div><div class="flex justify-between"><span class="text-stone-500">Status</span><b class="text-[#268c57]" x-text="payment==='cash' ? 'PENDING' : 'PAID'"></b></div><div class="flex justify-between text-lg"><span class="font-black">TOTAL</span><span class="font-black text-[#d51f32]" x-text="rupiah(total)"></span></div></div><p class="text-center text-[10px] text-stone-400">Kiosk kembali ke awal dalam <span x-text="receiptSeconds"></span> detik</p></div></div>
    </template>
  </section>
</div>`

Alpine.data('kiosk', () => ({
  step: 'lock', language: 'id', orderType: 'dine', category: 'rekomendasi', cart: [], current: null, modal: false, toast: false,
  custom: { chicken: '', drink: '', sauce: '' }, delivery: '', tableNumber: '', payment: '', queueNumber: 'PD-001', idleTimer: null, receiptTimer: null, receiptSeconds: 15,
  categories: [
    { id: 'rekomendasi', icon: 'fa-solid fa-fire', label: { id: 'Rekomen', en: 'Top picks' } }, { id: 'paket', icon: 'fa-solid fa-box', label: { id: 'Paket', en: 'Combos' } }, { id: 'alacarte', icon: 'fa-solid fa-drumstick-bite', label: { id: 'Satuan', en: 'A la carte' } }, { id: 'minuman', icon: 'fa-solid fa-glass-water', label: { id: 'Minum', en: 'Drinks' } }, { id: 'cemilan', icon: 'fa-solid fa-cookie-bite', label: { id: 'Cemilan', en: 'Snacks' } },
  ],
  payments: [{ id: 'qris', label: 'QRIS', icon: 'fa-solid fa-qrcode' }, { id: 'wallet', label: 'E-Wallet', icon: 'fa-solid fa-wallet' }, { id: 'bank', label: 'M-Banking', icon: 'fa-solid fa-building-columns' }, { id: 'debit', label: 'Debit', icon: 'fa-solid fa-credit-card' }, { id: 'cash', label: 'Cash', icon: 'fa-solid fa-money-bill-wave' }],
  init() { this.touch() },
  t(key) { return dict[this.language][key] || key },
  get visibleMenu() { return this.category === 'rekomendasi' ? menu.filter(x => x.category === 'rekomendasi') : menu.filter(x => x.category === this.category) },
  get total() { return this.cart.reduce((sum, line) => sum + line.price * line.qty, 0) },
  get itemCount() { return this.cart.reduce((sum, line) => sum + line.qty, 0) },
  get validTable() { const n = Number(this.tableNumber); return n >= 1 && n <= 99 },
  get canPay() { return this.delivery === 'counter' || (this.delivery === 'table' && this.validTable) },
  rupiah(value) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value) },
  go(next) { this.tap(); this.step = next; this.touch() },
  tap() { try { const ctx = new AudioContext(); const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.frequency.value = 620; gain.gain.setValueAtTime(.035, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + .07); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + .08) } catch (_) {} },
  touch() { clearTimeout(this.idleTimer); if (this.step !== 'lock' && this.step !== 'success' && this.step !== 'receipt') this.idleTimer = setTimeout(() => this.reset(), 60000) },
  openItem(item) { this.current = item; this.custom = { chicken: '', drink: '', sauce: '' }; this.modal = true; this.tap() },
  addCurrent() { if (!this.custom.chicken || !this.custom.drink || !this.custom.sauce) return; this.cart.push({ ...this.current, custom: { ...this.custom }, qty: 1, key: Date.now() }); this.modal = false; this.toast = true; this.tap(); setTimeout(() => this.toast = false, 1800) },
  changeQty(index, amount) { const next = this.cart[index].qty + amount; if (next < 1) this.cart.splice(index, 1); else this.cart[index].qty = next; this.tap(); if (!this.cart.length) this.go('menu') },
  keypad(value) { if (value === 'clear') this.tableNumber = ''; else if (value === 'delete') this.tableNumber = this.tableNumber.slice(0, -1); else if (this.tableNumber.length < 2) this.tableNumber += String(value); this.tap() },
  completeOrder() { this.tap(); this.queueNumber = `PD-${String(Math.floor(Math.random() * 900) + 100)}`; this.step = 'success'; setTimeout(() => { this.step = 'receipt'; this.startReceiptTimer() }, 2500) },
  startReceiptTimer() { this.receiptSeconds = 15; clearInterval(this.receiptTimer); this.receiptTimer = setInterval(() => { this.receiptSeconds--; if (this.receiptSeconds <= 0) { clearInterval(this.receiptTimer); this.reset() } }, 1000) },
  reset() { clearTimeout(this.idleTimer); clearInterval(this.receiptTimer); this.step = 'lock'; this.cart = []; this.category = 'rekomendasi'; this.current = null; this.modal = false; this.delivery = ''; this.tableNumber = ''; this.payment = ''; this.custom = { chicken: '', drink: '', sauce: '' } },
}))

Alpine.start()
